class Quizes {
  static List<String> questions = [
    "BODY FRAME/TYPE",
    "WALK & TALK",
    "WEATHER REACTION",
    "SWEATING",
    "APPETITE",
    "SKIN",
    "HAIR",
    "LIPS & TEETH",
    "EYES",
    "GENERAL SIGNS",
    //MENTAL
    "MEMORY",
    "MIND",
    "MIND ON ACTIONS",
    "SLEEP QUALITY",
    "EMOTIONAL NATURE",
  ];
  
  static List<String> option1 = [
    "Thin, bony and small framed. Hardly gain weight.",
    "Fast walk and talk.",
    "Enjoy warm climate but feel uncomfortable in cool weather.",
    "Sweat little but not much. Have minimal body odour.",
    "Irregular. Sometimes I feel hungry sometimes I don't.",
    "Normal to dry, rough, and thin and cool. Skin issues like dryness, dullness and wrinkly.",
    "Rough, dry and wavy. I get split ends easily.",
    "Have thin lips that tend to get dry. Teeth can be somewhat uneven. Teeth may require constant attention.",
    "Small in size. Feel dry and sleepy eyes often. I blink a lot.",
    "Cracking sound in joints. Small forehead. Nails crack easily.",
    "Quick to learn but quick to forget. Short term memory is good.",
    "Mind tends to get restless easily.",
    "Over-thinking",
    "Light and disturbed sleep, I wake up easily in the morning.",
    "I worry a lot. Often feel nervous and anxious.",
  ];
  static List<String> option2 = [
    "Medium built. Can gain or lose weight easily.",
    "Moderate and determined walk.",
    "Enjoy cool weather and dislike warm climate.",
    "Sweat a lot. Have medium body odour.",
    "Strong and sharp. Always feel hungry.",
    "Normal to oily, soft, reddish, sensitive and warm. Skin issues like inflammation.",
    "Normal, straight, thin and brownish.",
    "Medium sized soft lips. Upper lip slightly darker than lowe lip. Teeth are mediumsized but I tend to suffer from cavities.",
    "Medium in size. I often get reddish eyes.",
    "Black moles on body. Medium forehead. Nails are pink and soft.",
    "Average speed of learning. But once learnt, never forgets.",
    "Mind gets impatient or aggressive easily.",
    "Quick Implementation",
    "Moderate but regular. I can go back to sleep easily.",
    "I often get irritable, angry and impatient.",
  ];
  static List<String> option3 = [
    "Large built. Gain weight easily but difficult to lose.",
    "Slow and steady walk.",
    "Comfortable for most of the year but prefer summer and spring. Don't like damp climate.",
    "Sweat moderately but sweat a lot when working hard. Have strong body odour.",
    "Decent appetite. Have tendency to eat for comfort and taste.",
    "Normal to oily, soft, thick and cool. SKin issues like excessive oily itching, fungal infections.",
    "Thick, curly and oily. Hair colour tends to be on darker side.",
    "Large and smooth lips. Teeth are well formed and aligned and require less care in general.",
    "Big and attractive. I have thick eyes lashes.",
    "Disproportionate body like heavy thighs, hips etc. Large forehead. Nails are wide and whitish.",
    "Slow to learn but rememvers for a long time. Long term memory is good.",
    "Mind remain cool and calm. Mostly, unruffled.",
    "Lazy Implementation. Has a tendency to procrastinate.",
    "Deep and heavy. I can't easily wake up in morning.",
    "Loving and caring. It takes a lot to make me angry.",
  ];
}
